# Generated by Django 3.0.4 on 2020-03-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMail2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail2', models.EmailField(max_length=254)),
            ],
        ),
    ]
