# Generated by Django 3.0.4 on 2020-03-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0002_usermail2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail2',
            name='auto_send_mail2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermail2',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermail2',
            name='minute',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
