# Generated by Django 3.0.4 on 2020-03-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0003_auto_20200323_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMail',
        ),
    ]
