# Generated by Django 3.0.4 on 2020-03-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0004_delete_usermail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail2',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
