# Generated by Django 3.0.4 on 2020-03-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0005_usermail2_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail2',
            name='status',
        ),
    ]
