# Generated by Django 3.0.4 on 2020-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0009_auto_20200323_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMail2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail2', models.EmailField(max_length=254)),
                ('auto_send_mail2', models.BooleanField(default=False)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
