# Generated by Django 3.0.4 on 2020-03-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0011_remove_usermail2_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='auto_send_mail',
            field=models.BooleanField(default=True),
        ),
    ]
