# Generated by Django 3.0.4 on 2020-03-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0012_auto_20200324_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail2',
            name='auto_send_mail2',
            field=models.BooleanField(default=True),
        ),
    ]
