# Generated by Django 3.0.4 on 2020-03-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0014_auto_20200324_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail2',
            name='num1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermail2',
            name='num2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
