# Generated by Django 3.0.4 on 2020-03-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0015_auto_20200324_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail2',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='usermail2',
            name='num2',
        ),
    ]
