# Generated by Django 3.0.4 on 2020-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0016_auto_20200324_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail2',
            name='minute',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usermail2',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermail2',
            name='auto_send_mail2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermail2',
            name='hour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
