# Generated by Django 3.0.4 on 2020-03-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0017_auto_20200324_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMail',
        ),
    ]
