# Generated by Django 3.0.4 on 2020-03-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0018_delete_usermail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(blank=True, max_length=10, null=True)),
                ('minute', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=254)),
                ('auto_send_mail', models.BooleanField(default=False)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawldata.TimeSend')),
            ],
        ),
        migrations.DeleteModel(
            name='UserMail2',
        ),
    ]
