# Generated by Django 3.0.4 on 2020-03-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0019_auto_20200324_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail',
            name='time',
        ),
        migrations.AddField(
            model_name='timesend',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawldata.UserMail'),
        ),
    ]
