# Generated by Django 3.0.4 on 2020-03-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0020_auto_20200324_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesend',
            name='add',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
