# Generated by Django 3.0.4 on 2020-03-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0021_timesend_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesend',
            name='add',
        ),
    ]
