# Generated by Django 3.0.4 on 2020-04-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0022_remove_timesend_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail',
            name='auto_send_mail',
        ),
        migrations.AddField(
            model_name='usermail',
            name='hour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usermail',
            name='minute',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usermail',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TimeSend',
        ),
    ]
