# Generated by Django 3.0.4 on 2020-04-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawldata', '0023_auto_20200402_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermail',
            name='status',
        ),
    ]
